# pubspec.yaml

name: string_art_app
description: A circular string art generator from images.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3
  path_provider: ^2.1.1
  path: ^1.8.3
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter